##################################################################################################
###########################         UPDATE VARIABLE BELOW          ###############################
##################################################################################################

## Did you subscribed and agreed to the software terms for F5 BIG-IP VE - ALL (BYOL, 1 Boot Location) in AWS Marketplace?
## https://aws.amazon.com/marketplace/pp/B07G5MT2KT

AWS_ACCESS_KEY_ID: <key_id>
AWS_SECRET_ACCESS_KEY: <key_secret>

# A unique searchable prefix to all resources which are created
# Use a prefix w/o spaces or special characters (NO MORE THAN 10 CHARACTERS, no end with - or special characters)
PREFIX: udf-<name>

# Select on of  the region below (default US EST N. Virginia)
#us-east-1
#us-east-2
#us-west-1
#us-west-2
#us-west-3
#eu-central-1
#eu-west-1
#eu-west-2
#ap-southeast-1
#ap-southeast-2
#ap-northeast-1
#ap-northeast-2
DEFAULT_REGION: us-east-1
AWS_AZ_1A: us-east-1a
AWS_AZ_1B: us-east-1b

# Update your SSH AWS KEY (EC2 > NETWORK & SECURITY > Key Pairs)
AWS_SSH_KEY: <name_of_the_aws_key>

# Get the public IP of SEA-vBIGIP01.termmarc.com, go to Access Methods, e.g. nslookup 49efa5b7-224c-4e7b-9f04-cf52591ec443.access.udf.f5.com)
# Fill the IP address returned by the nslookup here
# /!\ IF THE IP ADDRESS ENDS WITH A x.x.x.0 (e.g. 129.43.54.0), DELETE YOUR DEPLOYMENT AND RESTART A NEW ONE.
CUSTOMER_GATEWAY_IP: 0.0.0.0

# Adjust the AMI based on your region (EC2 > IMAGES > AMIs > Public Images)
BYOL_BIGIP_AMI: "ami-58c3d327" # us-east-1 F5 Networks BIGIP-13.1.1-0.0.4 BYOL - All Modules 1 Boot Location
# See links for other AMI: https://github.com/F5Networks/f5-aws-cloudformation/tree/master/AMI%20Maps
#ap-south-1 ami-08fc42da3ff3a2d67
#eu-west-2 ami-10b14477
#eu-west-1 ami-5317f6be
#eu-west-3 ami-0146d8cbed1025718
#ap-northeast-2 ami-04eb9812dfb6c904a
#ap-northeast-1 ami-113f42fc
#sa-east-1 ami-00b63cf358955934b
#ca-central-1 ami-2151dc45
#ap-southeast-1 ami-36e5a6dc
#ap-southeast-2 ami-e15bfa83
#eu-central-1 ami-a2989449
#us-east-1 ami-58c3d327
#us-east-2 ami-2b4e4b4e
#us-west-1 ami-a24ea2c1
#us-west-2 ami-414e6b39

##################################################################################################
###############  DO NOT EDIT AFTER THIS LINE UNLESS YOU KNOW WHAT YOU ARE DOING  #################
##################################################################################################

# VPC cidr block should encompass the subnets you specify
VPC_CIDR_BLOCK: 172.17.0.0/16
SUBNET1_CIDR_BLOCK: 172.17.1.0/24
SUBNET2_CIDR_BLOCK: 172.17.2.0/24
# Ubuntu Web Server IP Address (in Subnet 2):
NODE_ADDRESS: 172.17.2.50
NODE_PORT: 80
VIRTUAL_SERVER_PORT: 80
POOL_MEMBER_PORT: 80

# ELB SCHEME (internet-facing or internal)
ELB_SCHEME: internet-facing
ELB_NAME: "{{PREFIX}}-elb"
APP_NAME: "{{PREFIX}}-app-aws"

# BIG-IP Customer Gateway Config
ansible_ssh_user: "admin"
ansible_ssh_pass: "purPl3f5@rk"

bigip_rest_user: "admin"
bigip_rest_password: "purPl3f5@rk"

# BIG-IQ SSG CONFIG
BIGIP_USER: admin
BIGIP_PWD: "74ZEws7axzWdKBap3DkQ"

BIGIQ_HOST: localhost:8100
BIGIQ_URI: http://{{BIGIQ_HOST}}
BIGIQ_USER: admin
BIGIQ_PWD: "purPl3f5@rk"

# IP Address of BIG IQ setup as license provider
# This BIQ must have netowrk access to the VPC in which the BIG-IP VE will be created
BYOL_BIGIQ_HOST: 10.1.10.4
BYOL_BIGIQ_USER: admin
BYOL_BIGIQ_PWD: "purPl3f5@rk"
#BYOL_POOL_NAME: byol-pool
BYOL_POOL_NAME: byol-pool-perAppVE

PROTOCOL_PROFILE_CLIENT: tcp-lan-optimized
PROTOCOL_PROFILE_SERVER: tcp-lan-optimized
HTTP_PROFILE: http
#Comma separated, string encapsulated list of DNS IP addresses. Leave the outer single quotes in place
NTP_SERVER: time.google.com

SSG_NAME:               "{{PREFIX}}-aws-ssg"
CLOUD_ENVIRONMENT_NAME: "{{PREFIX}}-aws-environment"
CLOUD_PROVIDER_NAME:    "{{PREFIX}}-aws-provider"
DEVICE_TEMPLATE_NAME:   "{{PREFIX}}-aws-device-template"
TEMPLATE_NODE_NAME:     "{{PREFIX}}-aws-service-node"
TEMPLATE_POOL_NAME:     "{{PREFIX}}-aws-pool"
SERVICE_CATALOG_NAME:   "{{PREFIX}}-aws-service-catalog"
LTM_RESOURCE_NAME:      "{{PREFIX}}-aws-resource-name"
